/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DacAdminRouteImport } from './routes/dac-admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingHikerRouteImport } from './routes/onboarding.hiker'
import { Route as OnboardingDriverRouteImport } from './routes/onboarding.driver'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated.requests'
import { Route as AuthenticatedRedlistRouteImport } from './routes/_authenticated.redlist'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPostRouteImport } from './routes/_authenticated.post'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated.payments'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated.feed'
import { Route as AuthenticatedTripIdRouteImport } from './routes/_authenticated.trip.$id'

const DacAdminRoute = DacAdminRouteImport.update({
  id: '/dac-admin',
  path: '/dac-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingHikerRoute = OnboardingHikerRouteImport.update({
  id: '/onboarding/hiker',
  path: '/onboarding/hiker',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDriverRoute = OnboardingDriverRouteImport.update({
  id: '/onboarding/driver',
  path: '/onboarding/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRedlistRoute = AuthenticatedRedlistRouteImport.update({
  id: '/redlist',
  path: '/redlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostRoute = AuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripIdRoute = AuthenticatedTripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/auth': typeof AuthRoute
  '/dac-admin': typeof DacAdminRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/redlist': typeof AuthenticatedRedlistRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/onboarding/driver': typeof OnboardingDriverRoute
  '/onboarding/hiker': typeof OnboardingHikerRoute
  '/trip/$id': typeof AuthenticatedTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/auth': typeof AuthRoute
  '/dac-admin': typeof DacAdminRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/redlist': typeof AuthenticatedRedlistRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/onboarding/driver': typeof OnboardingDriverRoute
  '/onboarding/hiker': typeof OnboardingHikerRoute
  '/trip/$id': typeof AuthenticatedTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/appeal': typeof AppealRoute
  '/auth': typeof AuthRoute
  '/dac-admin': typeof DacAdminRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/post': typeof AuthenticatedPostRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/redlist': typeof AuthenticatedRedlistRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/onboarding/driver': typeof OnboardingDriverRoute
  '/onboarding/hiker': typeof OnboardingHikerRoute
  '/_authenticated/trip/$id': typeof AuthenticatedTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeal'
    | '/auth'
    | '/dac-admin'
    | '/feed'
    | '/payments'
    | '/post'
    | '/profile'
    | '/redlist'
    | '/requests'
    | '/onboarding/driver'
    | '/onboarding/hiker'
    | '/trip/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeal'
    | '/auth'
    | '/dac-admin'
    | '/feed'
    | '/payments'
    | '/post'
    | '/profile'
    | '/redlist'
    | '/requests'
    | '/onboarding/driver'
    | '/onboarding/hiker'
    | '/trip/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/appeal'
    | '/auth'
    | '/dac-admin'
    | '/_authenticated/feed'
    | '/_authenticated/payments'
    | '/_authenticated/post'
    | '/_authenticated/profile'
    | '/_authenticated/redlist'
    | '/_authenticated/requests'
    | '/onboarding/driver'
    | '/onboarding/hiker'
    | '/_authenticated/trip/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AppealRoute: typeof AppealRoute
  AuthRoute: typeof AuthRoute
  DacAdminRoute: typeof DacAdminRoute
  OnboardingDriverRoute: typeof OnboardingDriverRoute
  OnboardingHikerRoute: typeof OnboardingHikerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dac-admin': {
      id: '/dac-admin'
      path: '/dac-admin'
      fullPath: '/dac-admin'
      preLoaderRoute: typeof DacAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/hiker': {
      id: '/onboarding/hiker'
      path: '/onboarding/hiker'
      fullPath: '/onboarding/hiker'
      preLoaderRoute: typeof OnboardingHikerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/driver': {
      id: '/onboarding/driver'
      path: '/onboarding/driver'
      fullPath: '/onboarding/driver'
      preLoaderRoute: typeof OnboardingDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/redlist': {
      id: '/_authenticated/redlist'
      path: '/redlist'
      fullPath: '/redlist'
      preLoaderRoute: typeof AuthenticatedRedlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post': {
      id: '/_authenticated/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trip/$id': {
      id: '/_authenticated/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof AuthenticatedTripIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPostRoute: typeof AuthenticatedPostRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRedlistRoute: typeof AuthenticatedRedlistRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedTripIdRoute: typeof AuthenticatedTripIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPostRoute: AuthenticatedPostRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRedlistRoute: AuthenticatedRedlistRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedTripIdRoute: AuthenticatedTripIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AppealRoute: AppealRoute,
  AuthRoute: AuthRoute,
  DacAdminRoute: DacAdminRoute,
  OnboardingDriverRoute: OnboardingDriverRoute,
  OnboardingHikerRoute: OnboardingHikerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
